namespace CaiPiao
{
    partial class Form_addData
    {
        /// <summary>
        /// 必需的设计器变量。
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// 清理所有正在使用的资源。
        /// </summary>
        /// <param name="disposing">如果应释放托管资源，为 true；否则为 false。</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows 窗体设计器生成的代码

        /// <summary>
        /// 设计器支持所需的方法 - 不要
        /// 使用代码编辑器修改此方法的内容。
        /// </summary>
        private void InitializeComponent()
        {
            this.groupPanel1 = new DevComponents.DotNetBar.Controls.GroupPanel();
            this.numericUpDown_qi = new System.Windows.Forms.NumericUpDown();
            this.groupPanel2 = new DevComponents.DotNetBar.Controls.GroupPanel();
            this.btn_redBallNumClear = new DevComponents.DotNetBar.ButtonX();
            this.btn_addRedBallNum = new DevComponents.DotNetBar.ButtonX();
            this.numericUpDown_redBall = new System.Windows.Forms.NumericUpDown();
            this.labelX1 = new DevComponents.DotNetBar.LabelX();
            this.groupPanel3 = new DevComponents.DotNetBar.Controls.GroupPanel();
            this.numericUpDown_blueBall = new System.Windows.Forms.NumericUpDown();
            this.btn_addDataOK = new DevComponents.DotNetBar.ButtonX();
            this.groupPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDown_qi)).BeginInit();
            this.groupPanel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDown_redBall)).BeginInit();
            this.groupPanel3.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDown_blueBall)).BeginInit();
            this.SuspendLayout();
            // 
            // groupPanel1
            // 
            this.groupPanel1.CanvasColor = System.Drawing.SystemColors.Control;
            this.groupPanel1.ColorSchemeStyle = DevComponents.DotNetBar.eDotNetBarStyle.Office2007;
            this.groupPanel1.Controls.Add(this.numericUpDown_qi);
            this.groupPanel1.Location = new System.Drawing.Point(12, 17);
            this.groupPanel1.Name = "groupPanel1";
            this.groupPanel1.Size = new System.Drawing.Size(156, 76);
            // 
            // 
            // 
            this.groupPanel1.Style.BackColor2SchemePart = DevComponents.DotNetBar.eColorSchemePart.PanelBackground2;
            this.groupPanel1.Style.BackColorGradientAngle = 90;
            this.groupPanel1.Style.BackColorSchemePart = DevComponents.DotNetBar.eColorSchemePart.PanelBackground;
            this.groupPanel1.Style.BorderBottom = DevComponents.DotNetBar.eStyleBorderType.Solid;
            this.groupPanel1.Style.BorderBottomWidth = 1;
            this.groupPanel1.Style.BorderColorSchemePart = DevComponents.DotNetBar.eColorSchemePart.PanelBorder;
            this.groupPanel1.Style.BorderLeft = DevComponents.DotNetBar.eStyleBorderType.Solid;
            this.groupPanel1.Style.BorderLeftWidth = 1;
            this.groupPanel1.Style.BorderRight = DevComponents.DotNetBar.eStyleBorderType.Solid;
            this.groupPanel1.Style.BorderRightWidth = 1;
            this.groupPanel1.Style.BorderTop = DevComponents.DotNetBar.eStyleBorderType.Solid;
            this.groupPanel1.Style.BorderTopWidth = 1;
            this.groupPanel1.Style.CornerDiameter = 4;
            this.groupPanel1.Style.CornerType = DevComponents.DotNetBar.eCornerType.Rounded;
            this.groupPanel1.Style.TextAlignment = DevComponents.DotNetBar.eStyleTextAlignment.Center;
            this.groupPanel1.Style.TextColorSchemePart = DevComponents.DotNetBar.eColorSchemePart.PanelText;
            this.groupPanel1.Style.TextLineAlignment = DevComponents.DotNetBar.eStyleTextAlignment.Near;
            this.groupPanel1.TabIndex = 0;
            this.groupPanel1.Text = "期数";
            // 
            // numericUpDown_qi
            // 
            this.numericUpDown_qi.Location = new System.Drawing.Point(46, 12);
            this.numericUpDown_qi.Maximum = new decimal(new int[] {
            300,
            0,
            0,
            0});
            this.numericUpDown_qi.Minimum = new decimal(new int[] {
            1,
            0,
            0,
            0});
            this.numericUpDown_qi.Name = "numericUpDown_qi";
            this.numericUpDown_qi.Size = new System.Drawing.Size(56, 21);
            this.numericUpDown_qi.TabIndex = 0;
            this.numericUpDown_qi.Value = new decimal(new int[] {
            1,
            0,
            0,
            0});
            // 
            // groupPanel2
            // 
            this.groupPanel2.CanvasColor = System.Drawing.SystemColors.Control;
            this.groupPanel2.ColorSchemeStyle = DevComponents.DotNetBar.eDotNetBarStyle.Office2007;
            this.groupPanel2.Controls.Add(this.btn_redBallNumClear);
            this.groupPanel2.Controls.Add(this.btn_addRedBallNum);
            this.groupPanel2.Controls.Add(this.numericUpDown_redBall);
            this.groupPanel2.Controls.Add(this.labelX1);
            this.groupPanel2.Location = new System.Drawing.Point(12, 104);
            this.groupPanel2.Name = "groupPanel2";
            this.groupPanel2.Size = new System.Drawing.Size(315, 125);
            // 
            // 
            // 
            this.groupPanel2.Style.BackColor2SchemePart = DevComponents.DotNetBar.eColorSchemePart.PanelBackground2;
            this.groupPanel2.Style.BackColorGradientAngle = 90;
            this.groupPanel2.Style.BackColorSchemePart = DevComponents.DotNetBar.eColorSchemePart.PanelBackground;
            this.groupPanel2.Style.BorderBottom = DevComponents.DotNetBar.eStyleBorderType.Solid;
            this.groupPanel2.Style.BorderBottomWidth = 1;
            this.groupPanel2.Style.BorderColorSchemePart = DevComponents.DotNetBar.eColorSchemePart.PanelBorder;
            this.groupPanel2.Style.BorderLeft = DevComponents.DotNetBar.eStyleBorderType.Solid;
            this.groupPanel2.Style.BorderLeftWidth = 1;
            this.groupPanel2.Style.BorderRight = DevComponents.DotNetBar.eStyleBorderType.Solid;
            this.groupPanel2.Style.BorderRightWidth = 1;
            this.groupPanel2.Style.BorderTop = DevComponents.DotNetBar.eStyleBorderType.Solid;
            this.groupPanel2.Style.BorderTopWidth = 1;
            this.groupPanel2.Style.CornerDiameter = 4;
            this.groupPanel2.Style.CornerType = DevComponents.DotNetBar.eCornerType.Rounded;
            this.groupPanel2.Style.TextAlignment = DevComponents.DotNetBar.eStyleTextAlignment.Center;
            this.groupPanel2.Style.TextColorSchemePart = DevComponents.DotNetBar.eColorSchemePart.PanelText;
            this.groupPanel2.Style.TextLineAlignment = DevComponents.DotNetBar.eStyleTextAlignment.Near;
            this.groupPanel2.TabIndex = 1;
            this.groupPanel2.Text = "红球";
            // 
            // btn_redBallNumClear
            // 
            this.btn_redBallNumClear.AccessibleRole = System.Windows.Forms.AccessibleRole.PushButton;
            this.btn_redBallNumClear.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btn_redBallNumClear.Location = new System.Drawing.Point(222, 64);
            this.btn_redBallNumClear.Name = "btn_redBallNumClear";
            this.btn_redBallNumClear.Size = new System.Drawing.Size(77, 22);
            this.btn_redBallNumClear.TabIndex = 3;
            this.btn_redBallNumClear.Text = "重新输入";
            this.btn_redBallNumClear.Click += new System.EventHandler(this.btn_redBallNumClear_Click);
            // 
            // btn_addRedBallNum
            // 
            this.btn_addRedBallNum.AccessibleRole = System.Windows.Forms.AccessibleRole.PushButton;
            this.btn_addRedBallNum.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btn_addRedBallNum.Location = new System.Drawing.Point(116, 64);
            this.btn_addRedBallNum.Name = "btn_addRedBallNum";
            this.btn_addRedBallNum.Size = new System.Drawing.Size(77, 22);
            this.btn_addRedBallNum.TabIndex = 2;
            this.btn_addRedBallNum.Text = "添加号码";
            this.btn_addRedBallNum.Click += new System.EventHandler(this.btn_addRedBallNum_Click);
            // 
            // numericUpDown_redBall
            // 
            this.numericUpDown_redBall.Location = new System.Drawing.Point(8, 65);
            this.numericUpDown_redBall.Maximum = new decimal(new int[] {
            33,
            0,
            0,
            0});
            this.numericUpDown_redBall.Minimum = new decimal(new int[] {
            1,
            0,
            0,
            0});
            this.numericUpDown_redBall.Name = "numericUpDown_redBall";
            this.numericUpDown_redBall.Size = new System.Drawing.Size(56, 21);
            this.numericUpDown_redBall.TabIndex = 1;
            this.numericUpDown_redBall.Value = new decimal(new int[] {
            1,
            0,
            0,
            0});
            // 
            // labelX1
            // 
            this.labelX1.BackColor = System.Drawing.Color.Silver;
            this.labelX1.Location = new System.Drawing.Point(8, 20);
            this.labelX1.Name = "labelX1";
            this.labelX1.Size = new System.Drawing.Size(291, 24);
            this.labelX1.TabIndex = 0;
            this.labelX1.Text = "号码:";
            // 
            // groupPanel3
            // 
            this.groupPanel3.CanvasColor = System.Drawing.SystemColors.Control;
            this.groupPanel3.ColorSchemeStyle = DevComponents.DotNetBar.eDotNetBarStyle.Office2007;
            this.groupPanel3.Controls.Add(this.numericUpDown_blueBall);
            this.groupPanel3.Location = new System.Drawing.Point(174, 17);
            this.groupPanel3.Name = "groupPanel3";
            this.groupPanel3.Size = new System.Drawing.Size(156, 76);
            // 
            // 
            // 
            this.groupPanel3.Style.BackColor2SchemePart = DevComponents.DotNetBar.eColorSchemePart.PanelBackground2;
            this.groupPanel3.Style.BackColorGradientAngle = 90;
            this.groupPanel3.Style.BackColorSchemePart = DevComponents.DotNetBar.eColorSchemePart.PanelBackground;
            this.groupPanel3.Style.BorderBottom = DevComponents.DotNetBar.eStyleBorderType.Solid;
            this.groupPanel3.Style.BorderBottomWidth = 1;
            this.groupPanel3.Style.BorderColorSchemePart = DevComponents.DotNetBar.eColorSchemePart.PanelBorder;
            this.groupPanel3.Style.BorderLeft = DevComponents.DotNetBar.eStyleBorderType.Solid;
            this.groupPanel3.Style.BorderLeftWidth = 1;
            this.groupPanel3.Style.BorderRight = DevComponents.DotNetBar.eStyleBorderType.Solid;
            this.groupPanel3.Style.BorderRightWidth = 1;
            this.groupPanel3.Style.BorderTop = DevComponents.DotNetBar.eStyleBorderType.Solid;
            this.groupPanel3.Style.BorderTopWidth = 1;
            this.groupPanel3.Style.CornerDiameter = 4;
            this.groupPanel3.Style.CornerType = DevComponents.DotNetBar.eCornerType.Rounded;
            this.groupPanel3.Style.TextAlignment = DevComponents.DotNetBar.eStyleTextAlignment.Center;
            this.groupPanel3.Style.TextColorSchemePart = DevComponents.DotNetBar.eColorSchemePart.PanelText;
            this.groupPanel3.Style.TextLineAlignment = DevComponents.DotNetBar.eStyleTextAlignment.Near;
            this.groupPanel3.TabIndex = 2;
            this.groupPanel3.Text = "兰球";
            // 
            // numericUpDown_blueBall
            // 
            this.numericUpDown_blueBall.Location = new System.Drawing.Point(46, 12);
            this.numericUpDown_blueBall.Maximum = new decimal(new int[] {
            16,
            0,
            0,
            0});
            this.numericUpDown_blueBall.Minimum = new decimal(new int[] {
            1,
            0,
            0,
            0});
            this.numericUpDown_blueBall.Name = "numericUpDown_blueBall";
            this.numericUpDown_blueBall.Size = new System.Drawing.Size(56, 21);
            this.numericUpDown_blueBall.TabIndex = 1;
            this.numericUpDown_blueBall.Value = new decimal(new int[] {
            1,
            0,
            0,
            0});
            // 
            // btn_addDataOK
            // 
            this.btn_addDataOK.AccessibleRole = System.Windows.Forms.AccessibleRole.PushButton;
            this.btn_addDataOK.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btn_addDataOK.Location = new System.Drawing.Point(117, 243);
            this.btn_addDataOK.Name = "btn_addDataOK";
            this.btn_addDataOK.Size = new System.Drawing.Size(105, 23);
            this.btn_addDataOK.TabIndex = 3;
            this.btn_addDataOK.Text = "确定添加数据";
            this.btn_addDataOK.Click += new System.EventHandler(this.btn_addDataOK_Click);
            // 
            // Form_addData
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 12F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(343, 278);
            this.Controls.Add(this.btn_addDataOK);
            this.Controls.Add(this.groupPanel3);
            this.Controls.Add(this.groupPanel2);
            this.Controls.Add(this.groupPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Location = new System.Drawing.Point(151, 25);
            this.Name = "Form_addData";
            this.StartPosition = System.Windows.Forms.FormStartPosition.Manual;
            this.Text = "Form_addData";
            this.groupPanel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDown_qi)).EndInit();
            this.groupPanel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDown_redBall)).EndInit();
            this.groupPanel3.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.numericUpDown_blueBall)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private DevComponents.DotNetBar.Controls.GroupPanel groupPanel1;
        private System.Windows.Forms.NumericUpDown numericUpDown_qi;
        private DevComponents.DotNetBar.Controls.GroupPanel groupPanel2;
        private DevComponents.DotNetBar.ButtonX btn_addRedBallNum;
        private System.Windows.Forms.NumericUpDown numericUpDown_redBall;
        private DevComponents.DotNetBar.LabelX labelX1;
        private DevComponents.DotNetBar.Controls.GroupPanel groupPanel3;
        private System.Windows.Forms.NumericUpDown numericUpDown_blueBall;
        private DevComponents.DotNetBar.ButtonX btn_addDataOK;
        private DevComponents.DotNetBar.ButtonX btn_redBallNumClear;
    }
}