namespace CaiPiao
{
    partial class Form_main
    {
        /// <summary>
        /// 必需的设计器变量。
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// 清理所有正在使用的资源。
        /// </summary>
        /// <param name="disposing">如果应释放托管资源，为 true；否则为 false。</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows 窗体设计器生成的代码

        /// <summary>
        /// 设计器支持所需的方法 - 不要
        /// 使用代码编辑器修改此方法的内容。
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form_main));
            this.sideBarPanelItem3 = new DevComponents.DotNetBar.SideBarPanelItem();
            this.buttonItem8 = new DevComponents.DotNetBar.ButtonItem();
            this.sideBarPanelItem2 = new DevComponents.DotNetBar.SideBarPanelItem();
            this.buttonItem5 = new DevComponents.DotNetBar.ButtonItem();
            this.sideBarPanelItem1 = new DevComponents.DotNetBar.SideBarPanelItem();
            this.buttonItem4 = new DevComponents.DotNetBar.ButtonItem();
            this.buttonItem6 = new DevComponents.DotNetBar.ButtonItem();
            this.buttonItem7 = new DevComponents.DotNetBar.ButtonItem();
            this.sideBar1 = new DevComponents.DotNetBar.SideBar();
            this.labelX1 = new DevComponents.DotNetBar.LabelX();
            this.bar1 = new DevComponents.DotNetBar.Bar();
            this.buttonItem1 = new DevComponents.DotNetBar.ButtonItem();
            this.buttonItem2 = new DevComponents.DotNetBar.ButtonItem();
            this.buttonItem3 = new DevComponents.DotNetBar.ButtonItem();
            this.labelX2 = new DevComponents.DotNetBar.LabelX();
            this.timer1 = new System.Windows.Forms.Timer(this.components);
            this.notifyIcon1 = new System.Windows.Forms.NotifyIcon(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.bar1)).BeginInit();
            this.SuspendLayout();
            // 
            // sideBarPanelItem3
            // 
            this.sideBarPanelItem3.BackgroundStyle.BackColor1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(255)))));
            this.sideBarPanelItem3.BackgroundStyle.BackColor2.Color = System.Drawing.Color.White;
            this.sideBarPanelItem3.BackgroundStyle.Border = DevComponents.DotNetBar.eBorderType.SingleLine;
            this.sideBarPanelItem3.BackgroundStyle.BorderColor.Color = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(86)))), ((int)(((byte)(113)))));
            this.sideBarPanelItem3.Cursor = System.Windows.Forms.Cursors.Hand;
            this.sideBarPanelItem3.HeaderHotStyle.BackColor1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(153)))), ((int)(((byte)(183)))));
            this.sideBarPanelItem3.HeaderHotStyle.BackColor2.Color = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(244)))), ((int)(((byte)(250)))));
            this.sideBarPanelItem3.HeaderHotStyle.GradientAngle = 90;
            this.sideBarPanelItem3.HeaderSideHotStyle.BackColor1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(153)))), ((int)(((byte)(183)))));
            this.sideBarPanelItem3.HeaderSideHotStyle.BackColor2.Color = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(244)))), ((int)(((byte)(250)))));
            this.sideBarPanelItem3.HeaderSideHotStyle.GradientAngle = 90;
            this.sideBarPanelItem3.HeaderSideStyle.BackColor1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(225)))), ((int)(((byte)(226)))), ((int)(((byte)(236)))));
            this.sideBarPanelItem3.HeaderSideStyle.BackColor2.Color = System.Drawing.Color.FromArgb(((int)(((byte)(126)))), ((int)(((byte)(125)))), ((int)(((byte)(157)))));
            this.sideBarPanelItem3.HeaderSideStyle.Border = DevComponents.DotNetBar.eBorderType.SingleLine;
            this.sideBarPanelItem3.HeaderSideStyle.BorderColor.Color = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(86)))), ((int)(((byte)(113)))));
            this.sideBarPanelItem3.HeaderSideStyle.BorderSide = ((DevComponents.DotNetBar.eBorderSide)(((DevComponents.DotNetBar.eBorderSide.Left | DevComponents.DotNetBar.eBorderSide.Top)
                        | DevComponents.DotNetBar.eBorderSide.Bottom)));
            this.sideBarPanelItem3.HeaderSideStyle.GradientAngle = 90;
            this.sideBarPanelItem3.HeaderStyle.BackColor1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(244)))), ((int)(((byte)(250)))));
            this.sideBarPanelItem3.HeaderStyle.BackColor2.Color = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(153)))), ((int)(((byte)(183)))));
            this.sideBarPanelItem3.HeaderStyle.Border = DevComponents.DotNetBar.eBorderType.SingleLine;
            this.sideBarPanelItem3.HeaderStyle.BorderColor.Color = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(86)))), ((int)(((byte)(113)))));
            this.sideBarPanelItem3.HeaderStyle.BorderSide = ((DevComponents.DotNetBar.eBorderSide)(((DevComponents.DotNetBar.eBorderSide.Right | DevComponents.DotNetBar.eBorderSide.Top)
                        | DevComponents.DotNetBar.eBorderSide.Bottom)));
            this.sideBarPanelItem3.HeaderStyle.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Bold);
            this.sideBarPanelItem3.HeaderStyle.ForeColor.Color = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(86)))), ((int)(((byte)(113)))));
            this.sideBarPanelItem3.HeaderStyle.GradientAngle = 90;
            this.sideBarPanelItem3.Name = "sideBarPanelItem3";
            this.sideBarPanelItem3.SubItems.AddRange(new DevComponents.DotNetBar.BaseItem[] {
            this.buttonItem8});
            this.sideBarPanelItem3.Text = "数据预测";
            this.sideBarPanelItem3.Click += new System.EventHandler(this.sideBarPanelItem3_Click);
            // 
            // buttonItem8
            // 
            this.buttonItem8.ButtonStyle = DevComponents.DotNetBar.eButtonStyle.ImageAndText;
            this.buttonItem8.ImagePaddingHorizontal = 8;
            this.buttonItem8.ImagePosition = DevComponents.DotNetBar.eImagePosition.Right;
            this.buttonItem8.Name = "buttonItem8";
            this.buttonItem8.Text = "概率预测";
            this.buttonItem8.Tooltip = "对可能出现的号码进行概率计算,帮您进行预测";
            this.buttonItem8.Click += new System.EventHandler(this.buttonItem8_Click);
            // 
            // sideBarPanelItem2
            // 
            this.sideBarPanelItem2.BackgroundStyle.BackColor1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(255)))));
            this.sideBarPanelItem2.BackgroundStyle.BackColor2.Color = System.Drawing.Color.White;
            this.sideBarPanelItem2.BackgroundStyle.Border = DevComponents.DotNetBar.eBorderType.SingleLine;
            this.sideBarPanelItem2.BackgroundStyle.BorderColor.Color = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(86)))), ((int)(((byte)(113)))));
            this.sideBarPanelItem2.Cursor = System.Windows.Forms.Cursors.Hand;
            this.sideBarPanelItem2.HeaderHotStyle.BackColor1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(153)))), ((int)(((byte)(183)))));
            this.sideBarPanelItem2.HeaderHotStyle.BackColor2.Color = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(244)))), ((int)(((byte)(250)))));
            this.sideBarPanelItem2.HeaderHotStyle.GradientAngle = 90;
            this.sideBarPanelItem2.HeaderSideHotStyle.BackColor1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(153)))), ((int)(((byte)(183)))));
            this.sideBarPanelItem2.HeaderSideHotStyle.BackColor2.Color = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(244)))), ((int)(((byte)(250)))));
            this.sideBarPanelItem2.HeaderSideHotStyle.GradientAngle = 90;
            this.sideBarPanelItem2.HeaderSideStyle.BackColor1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(225)))), ((int)(((byte)(226)))), ((int)(((byte)(236)))));
            this.sideBarPanelItem2.HeaderSideStyle.BackColor2.Color = System.Drawing.Color.FromArgb(((int)(((byte)(126)))), ((int)(((byte)(125)))), ((int)(((byte)(157)))));
            this.sideBarPanelItem2.HeaderSideStyle.Border = DevComponents.DotNetBar.eBorderType.SingleLine;
            this.sideBarPanelItem2.HeaderSideStyle.BorderColor.Color = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(86)))), ((int)(((byte)(113)))));
            this.sideBarPanelItem2.HeaderSideStyle.BorderSide = ((DevComponents.DotNetBar.eBorderSide)(((DevComponents.DotNetBar.eBorderSide.Left | DevComponents.DotNetBar.eBorderSide.Top)
                        | DevComponents.DotNetBar.eBorderSide.Bottom)));
            this.sideBarPanelItem2.HeaderSideStyle.GradientAngle = 90;
            this.sideBarPanelItem2.HeaderStyle.BackColor1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(244)))), ((int)(((byte)(250)))));
            this.sideBarPanelItem2.HeaderStyle.BackColor2.Color = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(153)))), ((int)(((byte)(183)))));
            this.sideBarPanelItem2.HeaderStyle.Border = DevComponents.DotNetBar.eBorderType.SingleLine;
            this.sideBarPanelItem2.HeaderStyle.BorderColor.Color = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(86)))), ((int)(((byte)(113)))));
            this.sideBarPanelItem2.HeaderStyle.BorderSide = ((DevComponents.DotNetBar.eBorderSide)(((DevComponents.DotNetBar.eBorderSide.Right | DevComponents.DotNetBar.eBorderSide.Top)
                        | DevComponents.DotNetBar.eBorderSide.Bottom)));
            this.sideBarPanelItem2.HeaderStyle.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Bold);
            this.sideBarPanelItem2.HeaderStyle.ForeColor.Color = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(86)))), ((int)(((byte)(113)))));
            this.sideBarPanelItem2.HeaderStyle.GradientAngle = 90;
            this.sideBarPanelItem2.Name = "sideBarPanelItem2";
            this.sideBarPanelItem2.SubItems.AddRange(new DevComponents.DotNetBar.BaseItem[] {
            this.buttonItem5});
            this.sideBarPanelItem2.Text = "数据管理";
            this.sideBarPanelItem2.Click += new System.EventHandler(this.sideBarPanelItem2_Click);
            // 
            // buttonItem5
            // 
            this.buttonItem5.ButtonStyle = DevComponents.DotNetBar.eButtonStyle.ImageAndText;
            this.buttonItem5.ImagePaddingHorizontal = 8;
            this.buttonItem5.ImagePosition = DevComponents.DotNetBar.eImagePosition.Right;
            this.buttonItem5.Name = "buttonItem5";
            this.buttonItem5.Text = "添加数据";
            this.buttonItem5.Tooltip = "添加新的双色球彩票获奖号码";
            this.buttonItem5.Click += new System.EventHandler(this.buttonItem5_Click);
            // 
            // sideBarPanelItem1
            // 
            this.sideBarPanelItem1.BackgroundStyle.BackColor1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(255)))));
            this.sideBarPanelItem1.BackgroundStyle.BackColor2.Color = System.Drawing.Color.White;
            this.sideBarPanelItem1.BackgroundStyle.Border = DevComponents.DotNetBar.eBorderType.SingleLine;
            this.sideBarPanelItem1.BackgroundStyle.BorderColor.Color = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(86)))), ((int)(((byte)(113)))));
            this.sideBarPanelItem1.Cursor = System.Windows.Forms.Cursors.Hand;
            this.sideBarPanelItem1.HeaderHotStyle.BackColor1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(153)))), ((int)(((byte)(183)))));
            this.sideBarPanelItem1.HeaderHotStyle.BackColor2.Color = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(244)))), ((int)(((byte)(250)))));
            this.sideBarPanelItem1.HeaderHotStyle.GradientAngle = 90;
            this.sideBarPanelItem1.HeaderSideHotStyle.BackColor1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(153)))), ((int)(((byte)(183)))));
            this.sideBarPanelItem1.HeaderSideHotStyle.BackColor2.Color = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(244)))), ((int)(((byte)(250)))));
            this.sideBarPanelItem1.HeaderSideHotStyle.GradientAngle = 90;
            this.sideBarPanelItem1.HeaderSideStyle.BackColor1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(225)))), ((int)(((byte)(226)))), ((int)(((byte)(236)))));
            this.sideBarPanelItem1.HeaderSideStyle.BackColor2.Color = System.Drawing.Color.FromArgb(((int)(((byte)(126)))), ((int)(((byte)(125)))), ((int)(((byte)(157)))));
            this.sideBarPanelItem1.HeaderSideStyle.Border = DevComponents.DotNetBar.eBorderType.SingleLine;
            this.sideBarPanelItem1.HeaderSideStyle.BorderColor.Color = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(86)))), ((int)(((byte)(113)))));
            this.sideBarPanelItem1.HeaderSideStyle.BorderSide = ((DevComponents.DotNetBar.eBorderSide)(((DevComponents.DotNetBar.eBorderSide.Left | DevComponents.DotNetBar.eBorderSide.Top)
                        | DevComponents.DotNetBar.eBorderSide.Bottom)));
            this.sideBarPanelItem1.HeaderSideStyle.GradientAngle = 90;
            this.sideBarPanelItem1.HeaderStyle.BackColor1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(244)))), ((int)(((byte)(250)))));
            this.sideBarPanelItem1.HeaderStyle.BackColor2.Color = System.Drawing.Color.FromArgb(((int)(((byte)(155)))), ((int)(((byte)(153)))), ((int)(((byte)(183)))));
            this.sideBarPanelItem1.HeaderStyle.Border = DevComponents.DotNetBar.eBorderType.SingleLine;
            this.sideBarPanelItem1.HeaderStyle.BorderColor.Color = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(86)))), ((int)(((byte)(113)))));
            this.sideBarPanelItem1.HeaderStyle.BorderSide = ((DevComponents.DotNetBar.eBorderSide)(((DevComponents.DotNetBar.eBorderSide.Right | DevComponents.DotNetBar.eBorderSide.Top)
                        | DevComponents.DotNetBar.eBorderSide.Bottom)));
            this.sideBarPanelItem1.HeaderStyle.Font = new System.Drawing.Font("Arial", 9F, System.Drawing.FontStyle.Bold);
            this.sideBarPanelItem1.HeaderStyle.ForeColor.Color = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(86)))), ((int)(((byte)(113)))));
            this.sideBarPanelItem1.HeaderStyle.GradientAngle = 90;
            this.sideBarPanelItem1.Name = "sideBarPanelItem1";
            this.sideBarPanelItem1.SubItems.AddRange(new DevComponents.DotNetBar.BaseItem[] {
            this.buttonItem4,
            this.buttonItem6,
            this.buttonItem7});
            this.sideBarPanelItem1.Text = "数据分析";
            this.sideBarPanelItem1.Click += new System.EventHandler(this.sideBarPanelItem1_Click);
            // 
            // buttonItem4
            // 
            this.buttonItem4.ButtonStyle = DevComponents.DotNetBar.eButtonStyle.ImageAndText;
            this.buttonItem4.ImagePaddingHorizontal = 8;
            this.buttonItem4.ImagePosition = DevComponents.DotNetBar.eImagePosition.Right;
            this.buttonItem4.Name = "buttonItem4";
            this.buttonItem4.Text = "各期总表";
            this.buttonItem4.Tooltip = "显示所有期的双色球彩票信息";
            this.buttonItem4.Click += new System.EventHandler(this.buttonItem4_Click);
            // 
            // buttonItem6
            // 
            this.buttonItem6.ButtonStyle = DevComponents.DotNetBar.eButtonStyle.ImageAndText;
            this.buttonItem6.ImagePaddingHorizontal = 8;
            this.buttonItem6.ImagePosition = DevComponents.DotNetBar.eImagePosition.Right;
            this.buttonItem6.Name = "buttonItem6";
            this.buttonItem6.Text = "号码统计";
            this.buttonItem6.Tooltip = "显示每个号码的出现次数";
            this.buttonItem6.Click += new System.EventHandler(this.buttonItem6_Click);
            // 
            // buttonItem7
            // 
            this.buttonItem7.ButtonStyle = DevComponents.DotNetBar.eButtonStyle.ImageAndText;
            this.buttonItem7.ImagePaddingHorizontal = 8;
            this.buttonItem7.ImagePosition = DevComponents.DotNetBar.eImagePosition.Right;
            this.buttonItem7.Name = "buttonItem7";
            this.buttonItem7.Text = "号码查找";
            this.buttonItem7.Tooltip = "查找获奖结果包含多于3位的要搜索的数字";
            this.buttonItem7.Click += new System.EventHandler(this.buttonItem7_Click);
            // 
            // sideBar1
            // 
            this.sideBar1.AccessibleRole = System.Windows.Forms.AccessibleRole.ToolBar;
            this.sideBar1.Appearance = DevComponents.DotNetBar.eSideBarAppearance.Flat;
            this.sideBar1.BackColor = System.Drawing.Color.LightSteelBlue;
            this.sideBar1.ColorScheme.ItemCheckedBackground = System.Drawing.Color.Empty;
            this.sideBar1.ColorScheme.ItemCheckedBorder = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(86)))), ((int)(((byte)(113)))));
            this.sideBar1.ColorScheme.ItemCheckedText = System.Drawing.Color.Black;
            this.sideBar1.ColorScheme.ItemExpandedBackground = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(142)))), ((int)(((byte)(75)))));
            this.sideBar1.ColorScheme.ItemExpandedBackground2 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(207)))), ((int)(((byte)(139)))));
            this.sideBar1.ColorScheme.ItemExpandedShadow = System.Drawing.Color.Empty;
            this.sideBar1.ColorScheme.ItemExpandedText = System.Drawing.Color.Black;
            this.sideBar1.ColorScheme.ItemHotBackground = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(244)))), ((int)(((byte)(204)))));
            this.sideBar1.ColorScheme.ItemHotBackground2 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(209)))), ((int)(((byte)(147)))));
            this.sideBar1.ColorScheme.ItemHotBorder = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(86)))), ((int)(((byte)(113)))));
            this.sideBar1.ColorScheme.ItemHotText = System.Drawing.Color.Black;
            this.sideBar1.ColorScheme.ItemPressedBackground = System.Drawing.Color.FromArgb(((int)(((byte)(254)))), ((int)(((byte)(142)))), ((int)(((byte)(75)))));
            this.sideBar1.ColorScheme.ItemPressedBackground2 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(207)))), ((int)(((byte)(139)))));
            this.sideBar1.ColorScheme.ItemPressedBorder = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(86)))), ((int)(((byte)(113)))));
            this.sideBar1.ColorScheme.ItemPressedText = System.Drawing.Color.Black;
            this.sideBar1.ColorScheme.ItemText = System.Drawing.Color.Black;
            this.sideBar1.ColorScheme.MenuBackground = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(232)))), ((int)(((byte)(232)))));
            this.sideBar1.ColorScheme.MenuBackground2 = System.Drawing.Color.White;
            this.sideBar1.ColorScheme.MenuBorder = System.Drawing.Color.FromArgb(((int)(((byte)(87)))), ((int)(((byte)(86)))), ((int)(((byte)(113)))));
            this.sideBar1.ColorScheme.MenuSide = System.Drawing.Color.FromArgb(((int)(((byte)(126)))), ((int)(((byte)(125)))), ((int)(((byte)(157)))));
            this.sideBar1.Cursor = System.Windows.Forms.Cursors.Hand;
            this.sideBar1.ExpandedPanel = this.sideBarPanelItem1;
            this.sideBar1.Font = new System.Drawing.Font("宋体", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.World);
            this.sideBar1.Location = new System.Drawing.Point(1, 25);
            this.sideBar1.Name = "sideBar1";
            this.sideBar1.Panels.AddRange(new DevComponents.DotNetBar.BaseItem[] {
            this.sideBarPanelItem1,
            this.sideBarPanelItem2,
            this.sideBarPanelItem3});
            this.sideBar1.Size = new System.Drawing.Size(151, 258);
            this.sideBar1.TabIndex = 1;
            this.sideBar1.Text = "sideBar1";
            // 
            // labelX1
            // 
            this.labelX1.BackColor = System.Drawing.Color.LightSteelBlue;
            this.labelX1.BorderType = DevComponents.DotNetBar.eBorderType.Raised;
            this.labelX1.Cursor = System.Windows.Forms.Cursors.SizeAll;
            this.labelX1.Font = new System.Drawing.Font("宋体", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.labelX1.ForeColor = System.Drawing.Color.Gray;
            this.labelX1.Location = new System.Drawing.Point(1, 1);
            this.labelX1.Name = "labelX1";
            this.labelX1.SingleLineColor = System.Drawing.SystemColors.ButtonFace;
            this.labelX1.Size = new System.Drawing.Size(424, 25);
            this.labelX1.Style = DevComponents.DotNetBar.eDotNetBarStyle.OfficeXP;
            this.labelX1.TabIndex = 2;
            this.labelX1.Text = "双色球彩票信息统计分析管理系统";
            this.labelX1.TextAlignment = System.Drawing.StringAlignment.Center;
            this.labelX1.MouseDown += new System.Windows.Forms.MouseEventHandler(this.labelX1_MouseDown);
            this.labelX1.MouseMove += new System.Windows.Forms.MouseEventHandler(this.labelX1_MouseMove);
            this.labelX1.MouseUp += new System.Windows.Forms.MouseEventHandler(this.labelX1_MouseUp);
            // 
            // bar1
            // 
            this.bar1.Items.AddRange(new DevComponents.DotNetBar.BaseItem[] {
            this.buttonItem1,
            this.buttonItem2,
            this.buttonItem3});
            this.bar1.Location = new System.Drawing.Point(425, 1);
            this.bar1.Name = "bar1";
            this.bar1.Size = new System.Drawing.Size(72, 25);
            this.bar1.Style = DevComponents.DotNetBar.eDotNetBarStyle.Office2003;
            this.bar1.TabIndex = 3;
            this.bar1.TabStop = false;
            this.bar1.Text = "bar1";
            // 
            // buttonItem1
            // 
            this.buttonItem1.Cursor = System.Windows.Forms.Cursors.Hand;
            this.buttonItem1.ImagePaddingHorizontal = 8;
            this.buttonItem1.Name = "buttonItem1";
            this.buttonItem1.Text = "—";
            this.buttonItem1.Tooltip = "最小化";
            this.buttonItem1.Click += new System.EventHandler(this.buttonItem1_Click);
            // 
            // buttonItem2
            // 
            this.buttonItem2.Cursor = System.Windows.Forms.Cursors.Hand;
            this.buttonItem2.ImagePaddingHorizontal = 8;
            this.buttonItem2.Name = "buttonItem2";
            this.buttonItem2.Text = "÷";
            this.buttonItem2.Tooltip = "隐藏为图标";
            this.buttonItem2.Click += new System.EventHandler(this.buttonItem2_Click);
            // 
            // buttonItem3
            // 
            this.buttonItem3.Cursor = System.Windows.Forms.Cursors.Hand;
            this.buttonItem3.ImagePaddingHorizontal = 8;
            this.buttonItem3.Name = "buttonItem3";
            this.buttonItem3.Text = "×";
            this.buttonItem3.Tooltip = "退出";
            this.buttonItem3.Click += new System.EventHandler(this.buttonItem3_Click);
            // 
            // labelX2
            // 
            this.labelX2.BackColor = System.Drawing.Color.LightSteelBlue;
            this.labelX2.BorderType = DevComponents.DotNetBar.eBorderType.Raised;
            this.labelX2.Cursor = System.Windows.Forms.Cursors.Default;
            this.labelX2.Font = new System.Drawing.Font("宋体", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(134)));
            this.labelX2.ForeColor = System.Drawing.Color.Gray;
            this.labelX2.Location = new System.Drawing.Point(1, 281);
            this.labelX2.Name = "labelX2";
            this.labelX2.SingleLineColor = System.Drawing.SystemColors.ButtonFace;
            this.labelX2.Size = new System.Drawing.Size(151, 25);
            this.labelX2.Style = DevComponents.DotNetBar.eDotNetBarStyle.OfficeXP;
            this.labelX2.TabIndex = 5;
            this.labelX2.Text = "日期时间";
            this.labelX2.TextAlignment = System.Drawing.StringAlignment.Center;
            // 
            // timer1
            // 
            this.timer1.Enabled = true;
            this.timer1.Interval = 1000;
            this.timer1.Tick += new System.EventHandler(this.timer1_Tick);
            // 
            // notifyIcon1
            // 
            this.notifyIcon1.Icon = ((System.Drawing.Icon)(resources.GetObject("notifyIcon1.Icon")));
            this.notifyIcon1.Text = "双色球彩票信息管理系统";
            this.notifyIcon1.MouseClick += new System.Windows.Forms.MouseEventHandler(this.notifyIcon1_MouseClick);
            // 
            // Form_main
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 12F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(499, 308);
            this.Controls.Add(this.labelX2);
            this.Controls.Add(this.bar1);
            this.Controls.Add(this.labelX1);
            this.Controls.Add(this.sideBar1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.IsMdiContainer = true;
            this.MaximumSize = new System.Drawing.Size(499, 308);
            this.Name = "Form_main";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "彩票信息统计管理系统";
            ((System.ComponentModel.ISupportInitialize)(this.bar1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private DevComponents.DotNetBar.SideBarPanelItem sideBarPanelItem3;
        private DevComponents.DotNetBar.SideBarPanelItem sideBarPanelItem2;
        private DevComponents.DotNetBar.SideBarPanelItem sideBarPanelItem1;
        private DevComponents.DotNetBar.SideBar sideBar1;
        private DevComponents.DotNetBar.LabelX labelX1;
        private DevComponents.DotNetBar.Bar bar1;
        private DevComponents.DotNetBar.ButtonItem buttonItem1;
        private DevComponents.DotNetBar.ButtonItem buttonItem2;
        private DevComponents.DotNetBar.ButtonItem buttonItem3;
        private DevComponents.DotNetBar.LabelX labelX2;
        private System.Windows.Forms.Timer timer1;
        private DevComponents.DotNetBar.ButtonItem buttonItem4;
        private DevComponents.DotNetBar.ButtonItem buttonItem5;
        private DevComponents.DotNetBar.ButtonItem buttonItem6;
        private DevComponents.DotNetBar.ButtonItem buttonItem7;
        private DevComponents.DotNetBar.ButtonItem buttonItem8;
        private System.Windows.Forms.NotifyIcon notifyIcon1;



    }
}

